[build]
  base = "app"
  command = "bunx tsr generate && vite build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY = "true"

[dev]
  command = "vite dev"
  port = 3000

[[redirects]]
  from = "https://lacostedesigns.netlify.app/*"
  to = "https://lacostedesigns.com/:splat"
  status = 301
  force = true
